import { useForm, Controller } from 'react-hook-form';
import { Box, Paper, TextField, Button, Grid, Typography, FormControlLabel, Switch, Alert, Divider } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { pageService } from '../../../services/pageService';
import { LoadingSpinner } from '../../../components/common/LoadingSpinner';
import { useEffect } from 'react';

interface PageFormData {
    title_en: string;
    title_bn: string;
    content_en: string;
    content_bn: string;
    slug: string;
    meta_title_en: string;
    meta_title_bn: string;
    meta_description_en: string;
    meta_description_bn: string;
    is_published: boolean;
}

export const AdminPageForm = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const queryClient = useQueryClient();
    const isEditMode = !!id;

    const { control, handleSubmit, reset, formState: { errors } } = useForm<PageFormData>({
        defaultValues: {
            title_en: '',
            title_bn: '',
            content_en: '',
            content_bn: '',
            slug: '',
            meta_title_en: '',
            meta_title_bn: '',
            meta_description_en: '',
            meta_description_bn: '',
            is_published: true,
        }
    });

    const { data: page, isLoading: isLoadingPage } = useQuery({
        queryKey: ['admin-page', id],
        queryFn: () => pageService.getById(Number(id)),
        enabled: isEditMode,
    });

    useEffect(() => {
        if (page) {
            reset(page);
        }
    }, [page, reset]);

    const mutation = useMutation({
        mutationFn: (data: PageFormData) => {
            if (isEditMode) {
                return pageService.update(Number(id), data);
            }
            return pageService.create(data);
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['admin-pages'] });
            navigate('/admin/pages');
        },
    });

    const onSubmit = (data: PageFormData) => {
        mutation.mutate(data);
    };

    if (isEditMode && isLoadingPage) return <LoadingSpinner />;
    if (mutation.isPending) return <LoadingSpinner />;

    return (
        <Box>
            <Typography variant="h4" fontWeight="bold" gutterBottom>
                {isEditMode ? 'Edit Page' : 'Create Page'}
            </Typography>

            <Paper sx={{ p: 4 }}>
                {mutation.isError && (
                    <Alert severity="error" sx={{ mb: 3 }}>
                        {(mutation.error as any)?.response?.data?.message || 'An error occurred'}
                    </Alert>
                )}

                <Box component="form" onSubmit={handleSubmit(onSubmit)} noValidate>
                    <Grid container spacing={3}>
                        <Grid item xs={12} md={6}>
                            <Controller
                                name="title_en"
                                control={control}
                                rules={{ required: 'Title (English) is required' }}
                                render={({ field }) => (
                                    <TextField {...field} label="Title (English)" fullWidth required error={!!errors.title_en} helperText={errors.title_en?.message} />
                                )}
                            />
                        </Grid>
                        <Grid item xs={12} md={6}>
                            <Controller
                                name="title_bn"
                                control={control}
                                render={({ field }) => (
                                    <TextField {...field} label="Title (Bangla)" fullWidth />
                                )}
                            />
                        </Grid>

                        <Grid item xs={12} md={6}>
                            <Controller
                                name="slug"
                                control={control}
                                render={({ field }) => (
                                    <TextField {...field} label="Slug (Optional)" fullWidth placeholder="Autogenerated if empty" helperText="URL friendly identifier" />
                                )}
                            />
                        </Grid>
                        <Grid item xs={12} md={6} sx={{ display: 'flex', alignItems: 'center' }}>
                            <Controller
                                name="is_published"
                                control={control}
                                render={({ field }) => (
                                    <FormControlLabel
                                        control={<Switch checked={field.value} onChange={field.onChange} />}
                                        label="Published"
                                    />
                                )}
                            />
                        </Grid>

                        <Grid item xs={12}>
                            <Controller
                                name="content_en"
                                control={control}
                                rules={{ required: 'Content (English) is required. Use HTML if needed.' }}
                                render={({ field }) => (
                                    <TextField {...field} label="Content (English)" multiline rows={8} fullWidth required error={!!errors.content_en} helperText={errors.content_en?.message} />
                                )}
                            />
                        </Grid>
                        <Grid item xs={12}>
                            <Controller
                                name="content_bn"
                                control={control}
                                render={({ field }) => (
                                    <TextField {...field} label="Content (Bangla)" multiline rows={8} fullWidth />
                                )}
                            />
                        </Grid>

                        <Grid item xs={12}><Divider sx={{ my: 2 }}><Typography variant="caption">SEO Metadata</Typography></Divider></Grid>

                        <Grid item xs={12} md={6}>
                            <Controller
                                name="meta_title_en"
                                control={control}
                                render={({ field }) => (
                                    <TextField {...field} label="Meta Title (EN)" fullWidth />
                                )}
                            />
                        </Grid>
                        <Grid item xs={12} md={6}>
                            <Controller
                                name="meta_title_bn"
                                control={control}
                                render={({ field }) => (
                                    <TextField {...field} label="Meta Title (BN)" fullWidth />
                                )}
                            />
                        </Grid>
                        <Grid item xs={12} md={6}>
                            <Controller
                                name="meta_description_en"
                                control={control}
                                render={({ field }) => (
                                    <TextField {...field} label="Meta Description (EN)" multiline rows={2} fullWidth />
                                )}
                            />
                        </Grid>
                        <Grid item xs={12} md={6}>
                            <Controller
                                name="meta_description_bn"
                                control={control}
                                render={({ field }) => (
                                    <TextField {...field} label="Meta Description (BN)" multiline rows={2} fullWidth />
                                )}
                            />
                        </Grid>

                        <Grid item xs={12} sx={{ display: 'flex', gap: 2, justifyContent: 'flex-end' }}>
                            <Button variant="outlined" onClick={() => navigate('/admin/pages')}>
                                Cancel
                            </Button>
                            <Button type="submit" variant="contained" size="large">
                                {isEditMode ? 'Update Page' : 'Create Page'}
                            </Button>
                        </Grid>
                    </Grid>
                </Box>
            </Paper>
        </Box>
    );
};
