import { useForm, Controller } from 'react-hook-form';
import { Box, Paper, TextField, Button, Grid, Typography, FormControlLabel, Switch, Alert } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { impactService } from '../../../services/impactService';
import { LoadingSpinner } from '../../../components/common/LoadingSpinner';
import { useEffect } from 'react';

interface ImpactFormData {
    metric_key: string;
    label_en: string;
    label_bn: string;
    value: number;
    icon: string;
    order: number;
    is_visible: boolean;
}

export const AdminImpactForm = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const queryClient = useQueryClient();
    const isEditMode = !!id;

    const { control, handleSubmit, reset, formState: { errors } } = useForm<ImpactFormData>({
        defaultValues: {
            metric_key: '',
            label_en: '',
            label_bn: '',
            value: 0,
            icon: '',
            order: 0,
            is_visible: true,
        }
    });

    const { data: metric, isLoading: isLoadingMetric } = useQuery({
        queryKey: ['impact-metric', id],
        queryFn: () => impactService.getById(Number(id)),
        enabled: isEditMode,
    });

    useEffect(() => {
        if (metric) {
            reset(metric);
        }
    }, [metric, reset]);

    const mutation = useMutation({
        mutationFn: (data: ImpactFormData) => {
            if (isEditMode) {
                return impactService.update(Number(id), data);
            }
            return impactService.create(data);
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['admin-impact'] });
            navigate('/admin/impact');
        },
    });

    const onSubmit = (data: ImpactFormData) => {
        mutation.mutate(data);
    };

    if (isEditMode && isLoadingMetric) return <LoadingSpinner />;
    if (mutation.isPending) return <LoadingSpinner />;

    return (
        <Box>
            <Typography variant="h4" fontWeight="bold" gutterBottom>
                {isEditMode ? 'Edit metric' : 'Add Metric'}
            </Typography>

            <Paper sx={{ p: 4 }}>
                {mutation.isError && (
                    <Alert severity="error" sx={{ mb: 3 }}>
                        {(mutation.error as any)?.response?.data?.message || 'An error occurred'}
                    </Alert>
                )}

                <Box component="form" onSubmit={handleSubmit(onSubmit)} noValidate>
                    <Grid container spacing={3}>
                        <Grid item xs={12} md={6}>
                            <Controller
                                name="label_en"
                                control={control}
                                rules={{ required: 'Label (English) is required' }}
                                render={({ field }) => (
                                    <TextField {...field} label="Label (English)" fullWidth required error={!!errors.label_en} helperText={errors.label_en?.message} />
                                )}
                            />
                        </Grid>
                        <Grid item xs={12} md={6}>
                            <Controller
                                name="label_bn"
                                control={control}
                                render={({ field }) => (
                                    <TextField {...field} label="Label (Bangla)" fullWidth />
                                )}
                            />
                        </Grid>

                        <Grid item xs={12} md={6}>
                            <Controller
                                name="value"
                                control={control}
                                rules={{ required: 'Value is required' }}
                                render={({ field }) => (
                                    <TextField {...field} type="number" label="Value (Number)" fullWidth required error={!!errors.value} helperText={errors.value?.message} />
                                )}
                            />
                        </Grid>
                        <Grid item xs={12} md={6}>
                            <Controller
                                name="metric_key"
                                control={control}
                                render={({ field }) => (
                                    <TextField {...field} label="Key (Optional, Unique)" fullWidth placeholder="Autogenerated if empty" />
                                )}
                            />
                        </Grid>

                        <Grid item xs={12} md={6}>
                            <Controller
                                name="icon"
                                control={control}
                                render={({ field }) => (
                                    <TextField {...field} label="Icon Name (MUI Icon)" fullWidth />
                                )}
                            />
                        </Grid>
                        <Grid item xs={12} md={6}>
                            <Controller
                                name="order"
                                control={control}
                                render={({ field }) => (
                                    <TextField {...field} type="number" label="Sort Order" fullWidth />
                                )}
                            />
                        </Grid>

                        <Grid item xs={12} sx={{ display: 'flex', alignItems: 'center' }}>
                            <Controller
                                name="is_visible"
                                control={control}
                                render={({ field }) => (
                                    <FormControlLabel
                                        control={<Switch checked={field.value} onChange={field.onChange} />}
                                        label="Visible"
                                    />
                                )}
                            />
                        </Grid>

                        <Grid item xs={12} sx={{ display: 'flex', gap: 2, justifyContent: 'flex-end' }}>
                            <Button variant="outlined" onClick={() => navigate('/admin/impact')}>
                                Cancel
                            </Button>
                            <Button type="submit" variant="contained" size="large">
                                {isEditMode ? 'Update Metric' : 'Create Metric'}
                            </Button>
                        </Grid>
                    </Grid>
                </Box>
            </Paper>
        </Box>
    );
};
