<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImportTeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $team_members = [

            [
                'name_en' => 'Anis A. Khan',
                'name_bn' => '',
                'role_en' => 'Trustee',
                'role_bn' => '',
                'category' => 'trustee',
                'photo' => 'team/anis_a_khan.jpg',
                'bio_en' => '“a distinguished figure in Bangladesh\'s corporate sphere, boasts over 40 years of expertise. An illustrious senior banker, Khan has held pivotal roles at ANZ Grindlays Bank, Standard Chartered Bank, and others. He chaired key associations like the Association of Bankers Bangladesh Limited (ABB) and Bangladesh Lease & Finance Companies Association (BLFCA). As the esteemed President of Bangladesh Cancer Aid Trust (BANCAT), he provides invaluable guidance and his heart lies in supporting cancer patients with care, hope, and strength. Under his compassionate leadership, BANCAT tirelessly works to alleviate the burdens of those battling cancer and to raise awareness across the nation”',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 0,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Shukla Sarwat Siraj',
                'name_bn' => '',
                'role_en' => 'Trustee',
                'role_bn' => '',
                'category' => 'trustee',
                'photo' => 'team/shukla_sarwat_siraj.jpg',
                'bio_en' => '“exemplifies unwavering dedication to civil rights and community welfare. Her roles as Treasurer of the Barristers’ Association of Bangladesh, General Secretary of the Gulshan Society, and General Member of the Law-and-Order Coordination Committee underscore her commitment. As Vice President of Legal & Corporate Affairs at BANCAT, she brings a heartfelt passion and personal investment to her duties, enriching every endeavor with genuine care.  ”',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Najmus Ahmed Albab',
                'name_bn' => '',
                'role_en' => 'Trustee',
                'role_bn' => '',
                'category' => 'trustee',
                'photo' => 'team/najmus_ahmed_albab.jpg',
                'bio_en' => '“is a dynamic social entrepreneur and inspiring public speaker. With 25 years of experience in the garment industry, he co-founded Valor of Bangladesh, emphasizing inclusive leadership and talent development and he is leading Lighthouse Bangladesh. He is a beacon of hope in Bangladesh\'s fight against cancer. As the author and executive director of  Bangladesh Cancer Aid Trust (BANCAT), he\'s dedicated to making cancer treatment accessible and spreading awareness nationwide. Having battled cancer himself,
                            Albab\'s personal journey fuels his commitment to helping others.Rokia Afzal Rahman (24 September 1941 – 5 April 2023) broke barriers as Bangladesh\'s first female bank manager, pioneering women\'s entrepreneurship and advocating for social causes. Founding the Women Entrepreneurs Association and Women in Small Enterprises, she propelled gender equality in business. She is the founding president of Bangladesh Cancer Aid Trust. Leading the Bangladesh Cancer Aid Trust showcased her commitment to societal welfare. 
                            ”',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Sohana Rouf Chowdhury',
                'name_bn' => '',
                'role_en' => 'Trustee',
                'role_bn' => '',
                'category' => 'trustee',
                'photo' => 'team/sohana_rouf_chowdhury.jpg',
                'bio_en' => '“Managing Director of Rangs Motors Limited, brings over 23 years of successful business leadership, she also serves as the PR Director at Lush Fresh Handmade Cosmetics, Singapore, and is the Founder of Amisheé Fine Jewelry. Committed to diversity, she leads impactful initiatives like the Dolonchapa project, addressing women\'s safety in public transport, and contributes to community welfare. brings her dynamic expertise to Bangladesh Cancer Aid Trust and her commitment shines brightly as BANCAT\'s Vice President in External Affairs.
                            The vibrant businessman and managing director of the Ejab Group, Mr. Eshtiaque Ahmed, is a shining example of social action. He demonstrates his devotion to community development through his crucial involvement in the Gulshan Youth Club, and his generosity is evident in his hard work as Joint Treasurer at BANCAT, where his organizational abilities make a substantial contribution to the trust\'s efforts. Eshtiaque is a real humanitarian and organizer who adds priceless skills to his economic ventures as well as his significant contributions to social causes.
                            ”',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Sabrina Shaheed',
                'name_bn' => '',
                'role_en' => 'Trustee',
                'role_bn' => '',
                'category' => 'trustee',
                'photo' => 'team/sabrina_shaheed.jpg',
                'bio_en' => '“a radiant beacon of hope and an esteemed educationist illuminates the path of countless youths as Principal of Sir John Wilson School in Bangladesh. Beyond her educational prowess, she embodies resilience and warmth, fostering holistic development within her students. As Vice President of Community Development at BANCAT, her profound commitment to education and unwavering spirit inspire transformative change.”',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Zeeshan Hasib',
                'name_bn' => '',
                'role_en' => 'Trustee',
                'role_bn' => '',
                'category' => 'trustee',
                'photo' => 'team/zeeshan_hasib.jpg',
                'bio_en' => '“a seasoned banking specialist, became a caring consultant. After two decades of service, he retired as Deputy Managing Director of a well-known national bank. As Treasurer and Director of Internal Audit at BANCAT, he devotes his time to sharing his extensive experience. His motivation is driven by personal tragedy, since he lost his father to cancer, which motivates him to make a difference.”',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Nehal Ahmed',
                'name_bn' => '',
                'role_en' => 'Trustee',
                'role_bn' => '',
                'category' => 'trustee',
                'photo' => 'team/nehal_ahmed.jpg',
                'bio_en' => '“Nehal Ahmed is a marketing expert, and board member of Renata Ltd., Society for Conservation of National Resources, (Aamartaka), and investor (SHEBA Platforms), with 25+ years of global B2C/B2B leadership. He has worked at Grameenphone/Telenor, Robi Axiata, Augere/Qubee, Bacardi Global, MARS Snackfoods Europe, and BAT Global in five industries and regions. He also contributes to the Impact Partner Advisory Committee at Sajida Foundation. Currently serving as Vice President of International Development at BANCAT, Nehal brings his extensive expertise and strategic insights to the organization\'s initiatives.”',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Farjad Ahmed',
                'name_bn' => '',
                'role_en' => 'Trustee',
                'role_bn' => '',
                'category' => 'trustee',
                'photo' => 'team/farjad_ahmed.jpg',
                'bio_en' => '“A. Farjad Ahmed is a distinguished banking professional and esteemed member of the Board of Trustees at the University of Asia Pacific, with a notable career spanning various roles in reputable organizations. With 28 years of experience, including a significant tenure at Standard Chartered Bank, he has excelled in leadership positions. As the Vice President & Director of finance at BANCAT, Farjad brings his wealth of expertise, and the organization is privileged to have him contribute to its mission.”',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Mahzabin Ferdous',
                'name_bn' => '',
                'role_en' => 'Trustee',
                'role_bn' => '',
                'category' => 'trustee',
                'photo' => 'team/mahzabin_ferdous.jpg',
                'bio_en' => '“a notable figure in Bangladesh, serves as the General Secretary of the Bangladesh Cancer Aid Trust (BANCAT). Her journey from corporate marketing to social entrepreneurship is inspiring. Co-founder & Managing Director of CThreeSixty Bangladesh and The Marvel-Be You, she also directs communications at Valor of Bangladesh. Recently she was listed on the ‘Kindness & Leadership, 50 Leading Lights Asia Pacific\' on World Kindness Day. As a trustee, her commitment to BANCAT is deeply personal, having lost her parents to cancer. Her leadership brings hope to those battling the disease in Bangladesh.”',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Zoheb Ahmed',
                'name_bn' => '',
                'role_en' => 'Trustee',
                'role_bn' => '',
                'category' => 'trustee',
                'photo' => 'team/zoheb_ahmed.jpg',
                'bio_en' => '“a dynamic professional, has left a mark in branding and marketing through his work at Apex Group and Akij Group. Currently, as Head of Category Development and Marketing at Runner Automobiles PLC, he brings his expertise to the automobile industry. As a Trustee of BANCAT, his infectious energy and sector insights drive positive change, benefiting the efforts in combating cancer.”',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Rumana Ahmed',
                'name_bn' => '',
                'role_en' => 'Trustee',
                'role_bn' => '',
                'category' => 'trustee',
                'photo' => 'team/rumana_ahmed.jpg',
                'bio_en' => '“a remarkable professional with a decorated career, currently holds the position of Head of Global Public Affairs at an MNC bank. She demonstrated her extensive knowledge in the business by holding the position of Head of Communications at GlaxoSmithKline Bangladesh Limited before her employment in the banking industry. Rumana is a privileged trustee for BANCAT, which gains from her knowledge and experience in international public affairs and communications. A prominent figure in Bangladesh\'s branding and marketing scene, Sajid Mahbub has held important roles at the IAA Bangladesh Chapter, Superbrands Bangladesh, Cannes Lions International Festival of Creativity, General Secretary of the Marketing Society of Bangladesh, and Chief Operating Officer & Executive Editor of the Bangladesh Brand Forum, among others. BANCAT benefits much from the experience and leadership he provides as a Trustee, as he is well known for his wide range of expertise.”',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Yusuf Tahdeebiddin Ahmed',
                'name_bn' => '',
                'role_en' => 'Trustee',
                'role_bn' => '',
                'category' => 'trustee',
                'photo' => 'team/yusuf_tahdeebiddin_ahmed.jpg',
                'bio_en' => '“a seasoned marketing expert, currently serves as Product Manager at IDEAMASN. With extensive experience at AITL and UUMOO, he co-founded eRMG, a testament to his industry influence. BANCAT, privileged to have him as a Trustee, values his expertise in Bangladesh\'s dynamic marketing landscape. His insights and achievements contribute significantly to BANCAT\'s strategic direction and success.
                            BANCAT is privileged to count Sohana Karim Yusuf as a Trustee, benefiting from her unwavering commitment to humanitarian causes. Her kindness and dedication are instrumental in advancing our mission to support the less fortunate. With Sohana\'s altruistic spirit guiding our efforts, BANCAT can make a meaningful difference in the lives of those in need.
                            ”',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 11,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Ms. Rubana Huq',
                'name_bn' => '',
                'role_en' => 'Vice-chancellor Asian University for Women',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/ms_rubana_huq.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Ms. Syeda Rizwana Hasan',
                'name_bn' => '',
                'role_en' => 'Chief Executive Bangladesh Environmental Lawyers Association (BELA)',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/ms_syeda_rizwana_hasan.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 13,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Ms. Sitara Ahsanullah',
                'name_bn' => '',
                'role_en' => 'President Bangladesh Mohila Samity',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/ms_sitara_ahsanullah.JPG',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 14,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Ms. Farzanah Chowdhury',
                'name_bn' => '',
                'role_en' => 'Managing Director & Chief Executive Officer Marks and Spencer',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/ms_farzanah_chowdhury.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 15,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Ms. Shwapna Bhowmick',
                'name_bn' => '',
                'role_en' => 'Country Manager Marks and Spencer',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/ms_shwapna_bhowmick.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 16,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Mr. Mirza Salman Ispahani',
                'name_bn' => '',
                'role_en' => 'Managing Director Mr. M M Ispahani Limited.',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/mr_mirza_salman_ispahani.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 17,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Mr. Syed Mahbubur Rahman',
                'name_bn' => '',
                'role_en' => 'Managing Director Mutual Trust Bank Ltd',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/mr_syed_mahbubur_rahman.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 18,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Mr. Munir Hasan',
                'name_bn' => '',
                'role_en' => 'Chief Coordinator, Digital Transformation and Youth Programme Prothom Alo',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/mr_munir_hasan.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 19,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Mr. Md Adil Hossain Noble',
                'name_bn' => '',
                'role_en' => 'Chief Enterprise Business Officer Robi Axiata Limited',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/mr_md_adil_hossain_noble.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 20,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Ms. Zahida Fizza Kabir',
                'name_bn' => '',
                'role_en' => 'Chief Executive Officer SAJIDA Foundation',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/ms_zahida_fizza_kabir.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 21,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Mr. Naser Ezaz',
                'name_bn' => '',
                'role_en' => 'Chief Executive Officer Standard Chartered Bank',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/mr_naser_ezaz.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 22,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Mr. MD Golam Kebria Sarkar',
                'name_bn' => '',
                'role_en' => 'Managing Director Studio of Creative Arts Limited',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/mr_md_golam_kebria_sarkar.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 23,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Prof. Imran Rahman',
                'name_bn' => '',
                'role_en' => 'Vice-Chancellor University of Liberal Arts Bangladesh',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/prof_imran_rahman.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 24,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Mr. Athar Ali Khan',
                'name_bn' => '',
                'role_en' => 'Cricket Commentator and Former Cricketer Bangladesh Cricket Board',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/mr_athar_ali_khan.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 25,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Mr. Sulaiman Ajanee',
                'name_bn' => '',
                'role_en' => 'Managing Director Standard Finis Oil Company',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/mr_sulaiman_ajanee.png',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 26,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Ms. Naheed Ezaher Khan',
                'name_bn' => '',
                'role_en' => 'Former Member Parliament',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/ms_naheed_ezaher_khan.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 27,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Ms. Rubaba Dowla',
                'name_bn' => '',
                'role_en' => 'Country Managing Director Oracle Bangladesh, Nepal and Bhutan',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/ms_rubaba_dowla.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 28,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Ms. Sara Zaker',
                'name_bn' => '',
                'role_en' => 'Member Sectretary Liberation War Museum at Liberation War Museum ; Mukti Juddho Jadughar Bangladesh',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/ms_sara_zaker.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 29,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Ms. Shampa Reza',
                'name_bn' => '',
                'role_en' => 'Artist & Social Activist Bangladesh Media Industry',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/ms_shampa_reza.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 30,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Ms. Suraiya Zannath',
                'name_bn' => '',
                'role_en' => 'Lead Financial Management Specialist Governance Global Practice, the World Bank',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/ms_suraiya_zannath.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 31,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Ms. Zara Jabeen Mahbub MP',
                'name_bn' => '',
                'role_en' => 'Member Standing Committee Ministry of Foreign Affairs',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/ms_zara_jabeen_mahbub_mp.jpg',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 32,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Prof. Dr. Golam Mohiuddin Faruque',
                'name_bn' => '',
                'role_en' => 'Project Director and Joint Secreary, Bangladesh Cancer Society Professor & Former Head, Department of Radiotherapy Dhaka Medical College',
                'role_bn' => '',
                'category' => 'ambassador',
                'photo' => 'team/prof_dr_golam_mohiuddin_faruque.JPG',
                'bio_en' => '',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 33,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name_en' => 'Late Ms. Rokia Afzal Rahman',
                'name_bn' => '',
                'role_en' => 'Founding President',
                'role_bn' => '',
                'category' => 'leadership',
                'photo' => 'team/late_ms_rokia_afzal_rahman.jpg',
                'bio_en' => 'In memory of our Founding President Late Ms. Rokia Afzal Rahman:Ms. Rokia Afzal Rahman, a beacon of compassion and leadership, forever resides in the hearts of those she touched through her unwavering commitment to humanity. As the Founding President of the Bangladesh Cancer Aid Trust, her legacy transcends time, leaving an indelible mark on the lives of countless individuals.Ms. Rahman\'s vision for the Bangladesh Cancer Aid Trust was not merely to provide temporary relief but to establish an en...',
                'bio_bn' => '',
                'email' => '',
                'linkedin' => '',
                'order' => 34,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('team_members')->insert($team_members);
    }
}
